apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-novaforge-notification-service
  labels:
  {{- include "novaforge-notification-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- include "novaforge-notification-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "novaforge-notification-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: novaforge-notification-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8088
              name: http
          env:
          {{- toYaml .Values.env | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
