apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-novaforge-file-service
  labels:
  {{- include "novaforge-file-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- include "novaforge-file-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "novaforge-file-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: novaforge-file-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8091
              name: http
          env:
          {{- toYaml .Values.env | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
