package com.novaforge.metadata.api;

import tools.jackson.databind.json.JsonMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The workflow register's honesty gate (PHASE-7 §12.3's requirement gate, raised to
 * the workflow tier): the dogfood is bound to <em>all</em> of erpplans' operational
 * workflows — every one of the 5,449 register rows (5,426 canonical + 23
 * parent/summary sub-workflows) sits in exactly one of three states, and a claim is
 * only as real as the e2e corpus that executes it:
 *
 * <ul>
 *   <li><strong>pinned</strong> — names suite file(s); each must exist on disk AND
 *       ride the live e2e corpus (the suites CI actually runs green), so a pin can
 *       never outlive its executable counterpart;</li>
 *   <li><strong>partial</strong> — the workflow's primary-linked requirement is
 *       claimed; the owning app must exist (the coverage gate's own rule);</li>
 *   <li><strong>uncovered</strong> — visible, wave-attributed where the upstream
 *       matrix links the workflow (honestly null where it does not yet).</li>
 * </ul>
 *
 * <p>The canon pins (5,426 / 5,449 / 1,396-3,295-758) fail loudly when the upstream
 * corpus moves: re-run {@code generate-workflow-coverage.py}, extend the workflow
 * map consciously, re-point. Generated by
 * {@code apps/buildright/scripts/generate-workflow-coverage.py} — do not hand-edit
 * {@code workflow-coverage/}.
 *
 * <p>The pins are <em>authored</em> on the hand-maintained {@code workflow-map.json},
 * so the gate walks that map too — in <em>both</em> directions, and across <em>both</em>
 * merge branches of the wave: an authored edit must ship with its regeneration (an
 * added or edited pin fails against the register), a register row whose state only a
 * map entry can produce must still have one (a deleted pin used to ship green with
 * the stale register behind it — the forty-fifth pass's hole), and a pin that omits
 * its {@code wave} key is compared through the generator's derived-wave fallback,
 * mirrored from committed inputs. The pin-realism contract — suites that exist and
 * ride the live corpus — holds on the authored surface as much as on the generated
 * one. The forty-fourth pass closed the hole where a map edit shipped green with a
 * stale register behind it; the forty-fifth closed the same class's other direction.
 */
class BuildrightWorkflowRegisterTests {

    private static final Path BUILDRIGHT = Path.of("..", "..", "apps", "buildright")
            .normalize().toAbsolutePath();
    private static final Path REPO_ROOT = BUILDRIGHT.resolve("..").resolve("..")
            .normalize().toAbsolutePath();

    /** The suites the e2e module actually executes green against the live stack —
     * the only suites a workflow pin may name. ErpSuiteCorpusE2ETest runs the
     * nine-suite Phase-7 corpus (the five acceptance suites beside the four
     * workflow-edge suites — GL, AR, costing, and the close-checklist); the O2C and
     * R2R cycle tests run their own; BuildRightProcureToPayE2ETest runs the three
     * P2P suites. Extending the corpus means extending this list in the same commit. */
    private static final Set<String> LIVE_E2E_CORPUS = Set.of(
        "apps/erp/suites/orderToCash.json",
        "apps/erp/suites/recordToReport.json",
        "apps/erp/suites/controls.json",
        "apps/erp/suites/inventoryCosting.json",
        "apps/erp/suites/creditAndCurrency.json",
        "apps/erp/suites/bankFeed.json",
        "apps/erp/suites/reconciliation.json",
        "apps/erp/suites/glLedgerEdges.json",
        "apps/erp/suites/arDocumentEdges.json",
        "apps/erp/suites/inventoryCostingEdges.json",
        "apps/erp/suites/closeChecklist.json",
        "apps/buildright/suites/p2pHappyPath.json",
        "apps/buildright/suites/p2pApprovalEdges.json",
        "apps/buildright/suites/p2pReceivingBillingEdges.json");

    private static final Set<String> KNOWN_APPS = Set.of("apps/erp", "apps/buildright");

    private static final JsonMapper MAPPER = JsonMapper.builder().build();

    @Test
    @DisplayName("the workflow register is committed, reconciles the erpplans canon, and every claim rides the live e2e corpus")
    @SuppressWarnings("unchecked")
    void workflowRegisterIsHonest() throws Exception {
        Path coverageJson = BUILDRIGHT.resolve("workflow-coverage").resolve("coverage.json");
        assertThat(coverageJson).as("run scripts/generate-workflow-coverage.py; commit "
                + "workflow-coverage/").exists();
        Map<String, Object> coverage = MAPPER.readValue(coverageJson.toFile(), Map.class);

        // the upstream canons — a failure here means erpplans moved: regenerate and
        // re-point the register consciously
        Map<String, Object> register = (Map<String, Object>) coverage.get("register");
        assertThat((Integer) register.get("rows"))
                .as("the classification register totals the erpplans canon (5,449 rows)")
                .isEqualTo(5449);
        assertThat((Integer) register.get("tier1")).as("register Tier 1 (canon)").isEqualTo(1396);
        assertThat((Integer) register.get("tier2")).as("register Tier 2 (canon)").isEqualTo(3295);
        assertThat((Integer) register.get("tier3")).as("register Tier 3 (canon)").isEqualTo(758);

        Map<String, Object> totals = (Map<String, Object>) coverage.get("totals");
        Map<String, Object> all = (Map<String, Object>) totals.get("all");
        int total = (Integer) all.get("total");
        assertThat(total)
                .as("the register covers every classified workflow (5,449 = 5,426 "
                        + "canonical + 23 sub-workflows)")
                .isEqualTo(5449);
        assertThat((Integer) totals.get("canonical")).isEqualTo(5426);
        assertThat((Integer) totals.get("subWorkflows")).isEqualTo(23);
        int pinned = (Integer) all.get("pinned");
        int partial = (Integer) all.get("partial");
        int uncovered = (Integer) all.get("uncovered");
        assertThat(pinned + partial + uncovered)
                .as("every workflow is in exactly one state")
                .isEqualTo(total);
        Map<String, Object> byTier = (Map<String, Object>) totals.get("byTier");
        assertThat(byTier).as("every workflow carries its criticality tier")
                .containsEntry("tier1", 1396).containsEntry("tier2", 3295)
                .containsEntry("tier3", 758);

        List<Map<String, Object>> workflows =
                (List<Map<String, Object>>) coverage.get("workflows");
        assertThat(workflows).hasSize(total);

        int seenPinned = 0;
        int seenPartial = 0;
        for (Map<String, Object> wf : workflows) {
            String id = String.valueOf(wf.get("id"));
            String status = String.valueOf(wf.get("status"));
            assertThat(Set.of("pinned", "partial", "uncovered"))
                    .as("%s status", id).contains(status);
            List<String> suites = (List<String>) wf.get("suites");
            switch (status) {
                case "pinned" -> {
                    seenPinned++;
                    assertThat(suites).as("%s names its suite pin(s)", id).isNotEmpty();
                    for (String suite : suites) {
                        assertThat(LIVE_E2E_CORPUS)
                                .as("%s pins via %s — a pin is only real if its suite "
                                        + "rides the live e2e corpus", id, suite)
                                .contains(suite);
                        assertThat(REPO_ROOT.resolve(suite))
                                .as("%s's pin %s exists on disk", id, suite).exists();
                    }
                }
                case "partial" -> {
                    seenPartial++;
                    // app claims may be compound ("apps/erp + apps/buildright") —
                    // each named app must be known and on disk (the coverage gate's
                    // own rule, mirrored)
                    String appField = String.valueOf(wf.get("app"));
                    for (String named : appField.split("\\s*\\+\\s*")) {
                        assertThat(KNOWN_APPS).as("%s claims app %s", id, named)
                                .contains(named.trim());
                        assertThat(REPO_ROOT.resolve(named.trim()))
                                .as("partial workflow %s's owning app %s exists", id, named)
                                .exists();
                    }
                }
                default -> { }
                // uncovered is the honest empty state — no pin, no app claim; the
                // wave is attribution only (null where the upstream matrix does not
                // yet link the workflow to any requirement)
            }
        }
        assertThat(seenPinned).as("the pinned count reconciles").isEqualTo(pinned);
        assertThat(seenPartial).as("the partial count reconciles").isEqualTo(partial);

        assertThat(BUILDRIGHT.resolve("workflow-coverage").resolve("matrix.md"))
                .as("the human-readable register rides the commit").exists();
    }

    @Test
    @DisplayName("the hand-maintained workflow map stays in sync with the committed register — both directions, every merge branch")
    @SuppressWarnings("unchecked")
    void workflowMapStaysInSyncWithTheRegister() throws Exception {
        Path mapPath = BUILDRIGHT.resolve("workflow-map.json");
        assertThat(mapPath).as("the hand-maintained pin map rides the commit").exists();
        Map<String, Object> map = MAPPER.readValue(mapPath.toFile(), Map.class);
        Map<String, Object> pins = (Map<String, Object>) map.get("workflows");
        Map<String, Object> coverage = MAPPER.readValue(
                BUILDRIGHT.resolve("workflow-coverage").resolve("coverage.json").toFile(), Map.class);
        Map<String, Map<String, Object>> register = new java.util.HashMap<>();
        for (Map<String, Object> wf : (List<Map<String, Object>>) coverage.get("workflows")) {
            register.put(String.valueOf(wf.get("id")), wf);
        }
        // the coverage-map feeds the derived-wave branch (generate-workflow-coverage
        // reads its prefix waves) — committed, so the mirror below can read it too
        Map<String, Object> coverageMap = MAPPER.readValue(
                BUILDRIGHT.resolve("coverage-map.json").toFile(), Map.class);
        Map<String, Object> prefixWaves = (Map<String, Object>) coverageMap.get("prefixes");

        // the map→register direction: an authored edit must ship with its regeneration
        for (var entry : pins.entrySet()) {
            String id = entry.getKey();
            Map<String, Object> pin = (Map<String, Object>) entry.getValue();
            Map<String, Object> row = register.get(id);
            assertThat(row).as("workflow-map.json pins %s but the register has no such row "
                    + "— re-run scripts/generate-workflow-coverage.py", id).isNotNull();
            assertPinMatchesRegister(id, pin, row, prefixWaves);
            // the pin-realism contract holds on the authored surface too, and every
            // named app (any status) is known and on disk
            for (String suite : sortedSuites(pin)) {
                assertThat(LIVE_E2E_CORPUS)
                        .as("%s pins via %s on workflow-map.json — a pin is only real if "
                                + "its suite rides the live e2e corpus", id, suite)
                        .contains(suite);
                assertThat(REPO_ROOT.resolve(suite))
                        .as("%s's map pin %s exists on disk", id, suite).exists();
            }
            String appField = String.valueOf(pin.get("app"));
            if (!"null".equals(appField)) {
                for (String named : appField.split("\\s*\\+\\s*")) {
                    assertThat(KNOWN_APPS).as("%s names app %s", id, named.trim())
                            .contains(named.trim());
                    assertThat(REPO_ROOT.resolve(named.trim()))
                            .as("%s's named app %s exists on disk", id, named.trim()).exists();
                }
            }
        }

        // the register→map direction (the forty-fifth pass): a register row whose
        // state only a map entry can produce must still have one — this leg used to
        // walk the map side only, so DELETING an authored pin shipped green with the
        // stale register row still claiming it (the requirements twin never had the
        // hole: it walks all 728 artifact rows against the map's merge)
        for (Map<String, Object> row : register.values()) {
            String id = String.valueOf(row.get("id"));
            if (!mustBeMapAuthored(row)) {
                continue;
            }
            Map<String, Object> pin = (Map<String, Object>) pins.get(id);
            assertThat(pins).as("the register's %s row is %s — a state only the map can "
                            + "author — but workflow-map.json has no entry for it (the pin was "
                            + "deleted without regenerating?) — re-run "
                            + "scripts/generate-workflow-coverage.py", id, row.get("status"))
                    .containsKey(id);
            assertThat(pin).as("workflow-map.json's %s entry is null — the pin was emptied "
                            + "without regenerating? — re-run scripts/generate-workflow-coverage.py", id)
                    .isNotNull();
            assertPinMatchesRegister(id, pin, row, prefixWaves);
        }
    }

    /** The generator's pin merge, mirrored: every authored field must equal the
     *  register row — and the wave comparison covers BOTH branches, an explicit map
     *  wave and the derived fallback the generator computes when the key is absent
     *  (itself a pure function of committed inputs, so the mirror is exact). */
    @SuppressWarnings("unchecked")
    private void assertPinMatchesRegister(String id, Map<String, Object> pin,
            Map<String, Object> row, Map<String, Object> prefixWaves) {
        assertThat(String.valueOf(pin.get("status")))
                .as("%s's map status diverges from the register — re-run "
                        + "scripts/generate-workflow-coverage.py", id)
                .isEqualTo(String.valueOf(row.get("status")));
        assertThat(sortedSuites(pin))
                .as("%s's map suite pins diverge from the register — re-run "
                        + "scripts/generate-workflow-coverage.py", id)
                .isEqualTo(row.get("suites"));
        assertThat(String.valueOf(pin.get("app")))
                .as("%s's map app diverges from the register", id)
                .isEqualTo(String.valueOf(row.get("app")));
        assertThat(String.valueOf(pin.getOrDefault("note", "")))
                .as("%s's map note diverges from the register", id)
                .isEqualTo(String.valueOf(row.get("note")));
        Object expectedWave = pin.containsKey("wave")
                ? pin.get("wave")
                : deriveWave((Map<String, List<String>>) row.get("requirements"), prefixWaves);
        assertThat(String.valueOf(expectedWave))
                .as("%s's %s wave diverges from the register — re-run "
                        + "scripts/generate-workflow-coverage.py", id,
                        pin.containsKey("wave") ? "map" : "map-derived")
                .isEqualTo(String.valueOf(row.get("wave")));
    }

    private static List<String> sortedSuites(Map<String, Object> pin) {
        List<String> suites = new java.util.ArrayList<>(
                (List<String>) pin.getOrDefault("suites", List.of()));
        java.util.Collections.sort(suites);
        return suites;
    }

    /** {@code generate-workflow-coverage.py}'s {@code derive_wave}, mirrored exactly:
     *  the minimum integer wave over the linked requirements' prefix waves (coverage-map
     *  prefix defaults — never a per-requirement override wave); else the first
     *  non-integer wave in primary-then-supporting order; else null. */
    @SuppressWarnings("unchecked")
    private Object deriveWave(Map<String, List<String>> links, Map<String, Object> prefixWaves) {
        List<Object> waves = new java.util.ArrayList<>();
        for (String kind : List.of("primary", "supporting")) {
            for (String reqId : links.getOrDefault(kind, List.of())) {
                String prefix = reqId.substring(0, reqId.lastIndexOf('-'));
                Map<String, Object> prefixDefault = (Map<String, Object>) prefixWaves.get(prefix);
                Object wave = prefixDefault == null ? null : prefixDefault.get("wave");
                if (wave != null) {
                    waves.add(wave);
                }
            }
        }
        Integer minInteger = null;
        for (Object wave : waves) {
            if (wave instanceof Integer i && (minInteger == null || i < minInteger)) {
                minInteger = i;
            }
        }
        if (minInteger != null) {
            return minInteger;
        }
        return waves.isEmpty() ? null : waves.getFirst();
    }

    /** A register row whose state only a map entry can produce: pinned (pins are the
     *  only source), partial with a hand-authored note (a derived partial's note is
     *  exactly the generator's template — the pattern mirrors it), or uncovered with
     *  an empty note (a derived uncovered note is never empty). If the generator's
     *  note templates ever change, this predicate changes in the same commit — the
     *  same coupling convention the merge mirrors carry. */
    private static final java.util.regex.Pattern DERIVED_PARTIAL_NOTE = java.util.regex.Pattern
            .compile("^exercises [A-Z]{2,4}-\\d{3}[a-z]? \\((covered|partial) via .+\\); no dedicated suite pin$");

    private boolean mustBeMapAuthored(Map<String, Object> row) {
        String status = String.valueOf(row.get("status"));
        String note = String.valueOf(row.get("note"));
        return switch (status) {
            case "pinned" -> true;
            case "partial" -> !DERIVED_PARTIAL_NOTE.matcher(note).matches();
            case "uncovered" -> note.isEmpty();
            default -> false;
        };
    }
}
