package com.novaforge.metadata.api;

import tools.jackson.databind.json.JsonMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The workflow register's honesty gate (PHASE-7 §12.3's requirement gate, raised to
 * the workflow tier): the dogfood is bound to <em>all</em> of erpplans' operational
 * workflows — every one of the 5,449 register rows (5,426 canonical + 23
 * parent/summary sub-workflows) sits in exactly one of three states, and a claim is
 * only as real as the e2e corpus that executes it:
 *
 * <ul>
 *   <li><strong>pinned</strong> — names suite file(s); each must exist on disk AND
 *       ride the live e2e corpus (the suites CI actually runs green), so a pin can
 *       never outlive its executable counterpart;</li>
 *   <li><strong>partial</strong> — the workflow's primary-linked requirement is
 *       claimed; the owning app must exist (the coverage gate's own rule);</li>
 *   <li><strong>uncovered</strong> — visible, wave-attributed, honest.</li>
 * </ul>
 *
 * <p>The canon pins (5,426 / 5,449 / 1,396-3,295-758) fail loudly when the upstream
 * corpus moves: re-run {@code generate-workflow-coverage.py}, extend the workflow
 * map consciously, re-point. Generated by
 * {@code apps/buildright/scripts/generate-workflow-coverage.py} — do not hand-edit
 * {@code workflow-coverage/}.
 */
class BuildrightWorkflowRegisterTests {

    private static final Path BUILDRIGHT = Path.of("..", "..", "apps", "buildright")
            .normalize().toAbsolutePath();
    private static final Path REPO_ROOT = BUILDRIGHT.resolve("..").resolve("..")
            .normalize().toAbsolutePath();

    /** The suites the e2e module actually executes green against the live stack —
     * the only suites a workflow pin may name. ErpSuiteCorpusE2ETest runs the eight
     * acceptance suites; ErpOrderToCashE2ETest and ErpRecordToReportE2ETest run their
     * own; BuildRightProcureToPayE2ETest runs the three P2P suites. Extending the
     * corpus means extending this list in the same commit. */
    private static final Set<String> LIVE_E2E_CORPUS = Set.of(
        "apps/erp/suites/orderToCash.json",
        "apps/erp/suites/recordToReport.json",
        "apps/erp/suites/controls.json",
        "apps/erp/suites/inventoryCosting.json",
        "apps/erp/suites/creditAndCurrency.json",
        "apps/erp/suites/bankFeed.json",
        "apps/erp/suites/reconciliation.json",
        "apps/erp/suites/glLedgerEdges.json",
        "apps/erp/suites/arDocumentEdges.json",
        "apps/erp/suites/inventoryCostingEdges.json",
        "apps/buildright/suites/p2pHappyPath.json",
        "apps/buildright/suites/p2pApprovalEdges.json",
        "apps/buildright/suites/p2pReceivingBillingEdges.json");

    private static final Set<String> KNOWN_APPS = Set.of("apps/erp", "apps/buildright");

    private static final JsonMapper MAPPER = JsonMapper.builder().build();

    @Test
    @DisplayName("the workflow register is committed, reconciles the erpplans canon, and every claim rides the live e2e corpus")
    @SuppressWarnings("unchecked")
    void workflowRegisterIsHonest() throws Exception {
        Path coverageJson = BUILDRIGHT.resolve("workflow-coverage").resolve("coverage.json");
        assertThat(coverageJson).as("run scripts/generate-workflow-coverage.py; commit "
                + "workflow-coverage/").exists();
        Map<String, Object> coverage = MAPPER.readValue(coverageJson.toFile(), Map.class);

        // the upstream canons — a failure here means erpplans moved: regenerate and
        // re-point the register consciously
        Map<String, Object> register = (Map<String, Object>) coverage.get("register");
        assertThat((Integer) register.get("rows"))
                .as("the classification register totals the erpplans canon (5,449 rows)")
                .isEqualTo(5449);
        assertThat((Integer) register.get("tier1")).as("register Tier 1 (canon)").isEqualTo(1396);
        assertThat((Integer) register.get("tier2")).as("register Tier 2 (canon)").isEqualTo(3295);
        assertThat((Integer) register.get("tier3")).as("register Tier 3 (canon)").isEqualTo(758);

        Map<String, Object> totals = (Map<String, Object>) coverage.get("totals");
        Map<String, Object> all = (Map<String, Object>) totals.get("all");
        int total = (Integer) all.get("total");
        assertThat(total)
                .as("the register covers every classified workflow (5,449 = 5,426 "
                        + "canonical + 23 sub-workflows)")
                .isEqualTo(5449);
        assertThat((Integer) totals.get("canonical")).isEqualTo(5426);
        assertThat((Integer) totals.get("subWorkflows")).isEqualTo(23);
        int pinned = (Integer) all.get("pinned");
        int partial = (Integer) all.get("partial");
        int uncovered = (Integer) all.get("uncovered");
        assertThat(pinned + partial + uncovered)
                .as("every workflow is in exactly one state")
                .isEqualTo(total);
        Map<String, Object> byTier = (Map<String, Object>) totals.get("byTier");
        assertThat(byTier).as("every workflow carries its criticality tier")
                .containsEntry("tier1", 1396).containsEntry("tier2", 3295)
                .containsEntry("tier3", 758);

        List<Map<String, Object>> workflows =
                (List<Map<String, Object>>) coverage.get("workflows");
        assertThat(workflows).hasSize(total);

        int seenPinned = 0;
        int seenPartial = 0;
        for (Map<String, Object> wf : workflows) {
            String id = String.valueOf(wf.get("id"));
            String status = String.valueOf(wf.get("status"));
            assertThat(Set.of("pinned", "partial", "uncovered"))
                    .as("%s status", id).contains(status);
            List<String> suites = (List<String>) wf.get("suites");
            switch (status) {
                case "pinned" -> {
                    seenPinned++;
                    assertThat(suites).as("%s names its suite pin(s)", id).isNotEmpty();
                    for (String suite : suites) {
                        assertThat(LIVE_E2E_CORPUS)
                                .as("%s pins via %s — a pin is only real if its suite "
                                        + "rides the live e2e corpus", id, suite)
                                .contains(suite);
                        assertThat(REPO_ROOT.resolve(suite))
                                .as("%s's pin %s exists on disk", id, suite).exists();
                    }
                }
                case "partial" -> {
                    seenPartial++;
                    // app claims may be compound ("apps/erp + apps/buildright") —
                    // each named app must be known and on disk (the coverage gate's
                    // own rule, mirrored)
                    String appField = String.valueOf(wf.get("app"));
                    for (String named : appField.split("\\s*\\+\\s*")) {
                        assertThat(KNOWN_APPS).as("%s claims app %s", id, named)
                                .contains(named.trim());
                        assertThat(REPO_ROOT.resolve(named.trim()))
                                .as("partial workflow %s's owning app %s exists", id, named)
                                .exists();
                    }
                }
                default -> { }
                // uncovered is the honest empty state — no pin, no app claim; the
                // wave is attribution only (null where the upstream matrix does not
                // yet link the workflow to any requirement)
            }
        }
        assertThat(seenPinned).as("the pinned count reconciles").isEqualTo(pinned);
        assertThat(seenPartial).as("the partial count reconciles").isEqualTo(partial);

        assertThat(BUILDRIGHT.resolve("workflow-coverage").resolve("matrix.md"))
                .as("the human-readable register rides the commit").exists();
    }
}
